{
 "title": "Aggregate UWS Stats",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Workspaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total workspaces created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from user_workspaces_server_workspace ;"
    }
   ]
  },
  {
   "title": "Users who have created workspaces",
   "type": "piechart",
   "description": "Of all users, count of those who have launched at least one workspace vs. those who have not.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(a.id)),\ncase when w.user_id_id is null then 'No workspaces' else '1 or more workspaces' end as has_workspace\nfrom \nauth_user a \nfull outer join user_workspaces_server_workspace w on w.user_id_id = a.id\ngroup by has_workspace;"
    }
   ]
  },
  {
   "title": "Workspaces by user",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "select\n  distinct(auth_user.username) as unique_users,\n  count(user_workspaces_server_workspace.id)\nfrom\n  user_workspaces_server_workspace\n  inner join auth_user on user_workspaces_server_workspace.user_id_id = auth_user.id\ngroup by\n  unique_users\norder by\n  count(user_workspaces_server_workspace.id) desc;"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average job duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select extract(epoch from (datetime_end-datetime_start)) as delta, job_type from user_workspaces_server_job;"
    }
   ]
  },
  {
   "title": "Jobs per job_type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select id, job_type from user_workspaces_server_job;"
    }
   ]
  },
  {
   "title": "Jobs by user",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select count(*) as c, a.username from user_workspaces_server_job w join auth_user a on a.id = w.user_id_id group by a.username order by c desc;\n"
    }
   ]
  }
 ]
}