{
 "title": "Time Range UWS Data",
 "description": "Select a time range to see associated data.",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Job initialization time",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  job_details :: jsonb -> 'metrics' -> 'time_init' as time_init\nfrom\n  user_workspaces_server_job\nwhere\n  datetime_created between '${__from:date:YYYY-MM-DD}'\n  and '${__to:date:YYYY-MM-DD}'\n  and job_details :: jsonb -> 'metrics' -> 'time_init' is not null\ngroup by\n  time_init\norder by\n  time_init;"
    }
   ]
  },
  {
   "title": "Job initializations taking longer than 5 minutes",
   "type": "stat",
   "description": "Explore panel data for ",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "select\n  id,\n  (job_details :: jsonb -> 'metrics' -> 'time_init')::integer / 60 as time_init_min\nfrom\n  user_workspaces_server_job\nwhere\n  datetime_created between '${__from:date:YYYY-MM-DD}'\n  and '${__to:date:YYYY-MM-DD}'\n  and (job_details :: jsonb -> 'metrics' -> 'time_init')::integer > 300;"
    }
   ]
  },
  {
   "title": "Workspaces created",
   "type": "timeseries",
   "description": "Count of workspaces created by year.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select\n $__timeGroupAlias(datetime_created, '1M'),\n count(id) as count\nfrom user_workspaces_server_workspace\nwhere $__timeFilter(datetime_created)\ngroup by 1\norder by $__timeGroup(datetime_created, '1M');"
    }
   ]
  },
  {
   "title": "Job durations",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select job_details :: jsonb -> 'metrics' -> 'time_init' as time_init, job_details :: jsonb -> 'metrics' -> 'time_pending' as time_pending, extract(seconds from (datetime_end - datetime_start)), datetime_start from user_workspaces_server_job where datetime_created between '${__from:date:YYYY-MM-DD}' and '${__to:date:YYYY-MM-DD}' order by datetime_start;"
    }
   ]
  }
 ]
}