version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: blank
      POSTGRES_USER: blank
    volumes:
      - custom_db_dir:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  web:
    build: .
    command: bash -c "docker/start.sh"
    volumes:
#      - This line should be how the host machine's user information is synced into the container
      - .:/code
      - /Users/jpuerto/user_workspaces_dir:/Users/jpuerto/user_workspaces_dir
    ports:
      - "5050:5050"
    depends_on:
      - redis
      - postgres
