version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/user-workspaces.conf:/etc/nginx/conf.d/user-workspaces.conf
# This can be file should be used in the case where the domain name between user-workspaces and proxying are different.
#      - ./docker/nginx/conf.d/passthrough.conf:/etc/nginx/conf.d/passthrough.conf
    ports:
      - "80:80"
    depends_on:
      - web
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: blank
      POSTGRES_USER: blank
    volumes:
      - ./db_dir:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - ./redis_dir:/data
    command: ["redis-server", "--appendonly", "yes"]
  web:
    build: .
    command: bash -c "docker/start.sh"
    volumes:
#     - This line should mount the host machine's user information into the container
      - .:/code
#     - This line should mount root_dir of main_storage onto docker container
    environment:
      - POSTGRES_PASSWORD=blank
      - POSTGRES_USER=blank
    depends_on:
      - redis
      - postgres
  django-q:
    build: .
    command: python manage.py qcluster
    volumes:
#     - This line should mount the host machine's user information into the container
      - .:/code
    environment:
      - POSTGRES_PASSWORD=blank
      - POSTGRES_USER=blank
    depends_on:
      - web