# Generated by Django 3.2.10 on 2022-01-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_workspaces_server", "0002_auto_20211214_2112"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="user_id",
        ),
    ]
