# Generated by Django 3.2.10 on 2022-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces_server', '0003_remove_job_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='datetime_created',
            field=models.DateTimeField(default='2022-01-31 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='resource_job_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
