# Generated by Django 3.2.10 on 2022-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_workspaces_server", "0004_auto_20220131_2151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="datetime_start",
            field=models.DateTimeField(null=True),
        ),
    ]
