# Generated by Django 4.1.2 on 2024-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces_server', '0010_job_user_id_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='default_job_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
