# Generated by Django 4.1.2 on 2024-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces_server', '0012_job_resource_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='disk_space',
            field=models.BigIntegerField(default=0),
        ),
    ]
