# Generated by Django 4.1.2 on 2025-01-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_workspaces_server", "0013_alter_workspace_disk_space"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedWorkspaceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_params", models.JSONField(blank=True, null=True)),
                ("last_job_type", models.CharField(max_length=64, null=True)),
                (
                    "original_workspace_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_workspace_set",
                        to="user_workspaces_server.workspace",
                    ),
                ),
                (
                    "shared_workspace_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_workspace_set",
                        to="user_workspaces_server.workspace",
                    ),
                ),
            ],
        ),
    ]
