# Generated by Django 4.1.2 on 2025-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_workspaces_server", "0014_sharedworkspacemapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedworkspacemapping",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
