# Generated by Django 4.2.17 on 2025-01-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_workspaces_server", "0015_sharedworkspacemapping_is_accepted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedworkspacemapping",
            old_name="last_params",
            new_name="last_resource_options",
        ),
    ]
