# Generated by Django 4.2.17 on 2025-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_workspaces_server",
            "0016_rename_last_params_sharedworkspacemapping_last_resource_options",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedworkspacemapping",
            name="datetime_share_created",
            field=models.DateTimeField(default=""),
            preserve_default=False,
        ),
    ]
