# Generated by Django 4.2.17 on 2025-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_workspaces_server",
            "0017_sharedworkspacemapping_datetime_share_created",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedworkspacemapping",
            name="datetime_share_created",
            field=models.DateTimeField(null=True),
        ),
    ]
