# Generated by Django 5.1.3 on 2025-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces_server', '0017_sharedworkspacemapping_datetime_share_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='datetime_last_job_launch',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='datetime_last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
