name: Linters

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==7.0.0 black==24.2.0 isort==5.13.2
    - name: Flake8 Lint
      run: |
        flake8 --ignore=E501,W503 src
    - name: Black Lint
      run: |
        black --line-length 99 --check --diff src
    - name: isort Lint
      run: |
        isort --profile black --check-only --diff src
